### PR TITLE
Remove ability to select errors bboxes from tree

### PR DESCRIPTION
**Pull request by GribovskyPavel**

### CODE REVIEW

**Comment by KateOrient** [comment]
[The website crashes when filters are reset and then applied](https://trello.com/c/65ujRJrv/533-the-website-crashes-when-filters-are-reset-and-then-applied)

**Comment by KateOrient** [comment]
[Highlight only structure element on the view when the user clicks on the elements in the structure tree panel](https://trello.com/c/0ic3O56n/531-highlight-only-structure-element-on-the-view-when-the-user-clicks-on-the-elements-in-the-structure-tree-panel)

**Comment by KateOrient** [comment]
[Highlight only structure element on the view when the user clicks on the elements in the structure tree panel](https://trello.com/c/0ic3O56n/531-highlight-only-structure-element-on-the-view-when-the-user-clicks-on-the-elements-in-the-structure-tree-panel)

**Comment by GribovskyPavel** [comment]
[Fix the scroll](https://trello.com/c/tp2IkYBx/528-fix-the-scroll)

**Pull request merged**
